### ISSUE TITLE
"Performer" tag removed from 320 and V0 transcodes

### ISSUE THREAD

**Issue by secure-username** [RogueOneEcho/caesura#104]
I created 16 bit flac, 320, and V0 transcodes from a 24 bit flac source. The 24 bit source has a performer set in all tracks. The 16 bit flac transcode retained the performer, but the 320 and V0 transcodes did not.

**Comment by RogueOneEcho** [comment]
Can you share the `torrent_id` number of the source?

Flac uses vorbis format for tags so they can be exactly replicated from 24 bit to 16 bit.

MP3 however uses ID3 so the tags are mapped using lofty-rs. The likelihood is the vorbis performer tag on the FLAC source doesn't properly follow the spec so it's getting rejected.

Was there anything in the logs?

If you share the `torrent_id` I can look more closely.

**Comment by secure-username** [comment]
Source torrent ID 4248871. No errors or warnings in the logs.

**Comment by RogueOneEcho** [comment]
tl;dr

Performer is the same as artist so it's not an issue that it's not included in the MP3.

---

The source FLAC does have a valid `PERFORMER` tag in the vorbis comment which matches the spec: https://xiph.org/vorbis/doc/Vorbis_I_spec.html

This can be checked with:
```bash
metaflac --list --block-type=VORBIS_COMMENT "path/to/track.flac"
```

And indeed this isn't copied to MP3. Checked with:

```bash
eyeD3 "path/to/track.mp3"
```

caesura uses [lofty-rs](https://github.com/Serial-ATA/lofty-rs) to read and write tags.

Lofty does support the vorbis performer tag:
https://github.com/Serial-ATA/lofty-rs/blob/dd4e926db4eaec593b051c34717a7fbae162397f/lofty/src/tag/item.rs#L365

But it doesn't have a mapping to convert PERFORMER to ID3v2
https://github.com/Serial-ATA/lofty-rs/blob/dd4e926db4eaec593b051c34717a7fbae162397f/lofty/src/tag/item.rs#L139-L231

ChatGPT says:

> In ID3v2, there is no standard frame specifically named PERFORMER. The most closely related ID3v2 frame is TPE1 (Lead performer/soloist), TPE2 (Band/orchestra/accompaniment), or TIPL (Involved people list). However, these frames have distinct meanings and are not universally used for PERFORMER.

Checking the ID3v2 spec confirms this: https://mutagen-specs.readthedocs.io/en/latest/id3/id3v2.4.0-frames.html

`TPE1` is already mapped to `ARTIST` https://github.com/Serial-ATA/lofty-rs/blob/dd4e926db4eaec593b051c34717a7fbae162397f/lofty/src/tag/item.rs#L157
https://github.com/Serial-ATA/lofty-rs/blob/dd4e926db4eaec593b051c34717a7fbae162397f/lofty/src/tag/item.rs#L354

So it does make sense to ignore the PERFORMER tag
