### ISSUE TITLE
Inaccurate timestamps in transcode logs

### ISSUE THREAD

**Issue by secure-username** [RogueOneEcho/caesura#105]
The timestamp on the info level log showing the progress of a transcode is the time when the transcode command started, not the time when the log is made.

This is most obvious when running a batch transcode. After hundreds of transcodes, the timestamp in each progress log is 40 minutes behind the timestamps in surrounding logs: https://i.ibb.co/hRh2hkP/timestamps.png

**Comment by RogueOneEcho** [comment]
Yeah, that has been annoying me for a while.

Finally fixed in 01a76c84
