### ISSUE TITLE
File names in torrents must be less than 180 characters

### ISSUE THREAD

**Issue by RogueOneEcho** [RogueOneEcho/caesura#24]
The indexer API requires that the path (directory + file name) of each file in a torrent are less than 180 characters.

`red_oxide` contained some logic for this but due to bugs some would slip through.

`caesura` solves this in a few ways:
- Each track is checked to confirm its path meets the criteria
- [Alternative names for tracks are suggested if they are too long](https://github.com/RogueOneEcho/caesura/blob/main/src/naming/shortener.rs)
- #22 is resolved which lead to unnecessary characters
- A shorter naming convention for transcodes is used:
  - `Dido - Life for Rent [2008] (WEB - MP3 - V0)` by `red_oxide`
  - `Dido - Life for Rent [2008] [WEB V0]` by `caesura` (8 characters shorter)

**Comment by predictablefoley** [comment]
is it possible that the limits have increase since this change, now making it impossible to upload torrents with longer filenames via caesura even though they are allowed by the tracker?

**Comment by RogueOneEcho** [comment]
> is it possible that the limits have increase since this change, now making it impossible to upload torrents with longer filenames via caesura even though they are allowed by the tracker?

Can you give me an example?

The rules are unchanged as far as I'm aware:

> 2.3.12. The maximum character length for files is 180 characters.

**Comment by predictablefoley** [comment]
> > is it possible that the limits have increase since this change, now making it impossible to upload torrents with longer filenames via caesura even though they are allowed by the tracker?
> 
> Can you give me an example?
> 
> RED's upload rules are unchanged as far as I'm aware:
> 
> > 2.3.12. The maximum character length for files is 180 characters.

my apologies, i was mistaken due to an error in one of my scripts.

for posterity, the path length limit is evaluated on the string starting from the name of the top-level sub-directory of the torrent without the leading slash/backslash, for instance, "torrent-dir/disc-dir/file.ext".
