### ISSUE TITLE
Outputted Torrent files should be marked completed

### ISSUE THREAD

**Issue by mat926** [RogueOneEcho/caesura#91]
The output torrent files that get created has a TorrentState Enum of  `pausedDL` or `PAUSED_DOWNLOAD`. This causes issues with tools like qBit_manage where it checks the complete status and these torrents do not get rechecked automatically. Is it possible to have them marked as complete as the .torrents are being generated?

**Comment by RogueOneEcho** [comment]
As far as I'm aware torrent files themselves don't have a paused state? Isn't it the torrent client responsible for that? As such I believe this would be an issue with qBit or qBit_manage.

**Comment by RogueOneEcho** [comment]
I agree that direct injection would be the best solution for this. I'll close this issue in favor of the ideas discussion: https://github.com/RogueOneEcho/caesura/discussions/90
