### ISSUE TITLE
RED changed URLs.

### ISSUE THREAD

**Issue by quig-official** [RogueOneEcho/caesura#92]
The TLD is now `.sh` instead of `.ch`

~~Uploads are turned off for right now. But, hopefully, this will be as simple as pointing to a new domain and it will work when uploads are back.~~

**Comment by RogueOneEcho** [comment]
Adding the following to `config.yml` should be all that is required.

```yaml
indexer_url: https://redacted.sh
```

I'll look into updating the default when I have capacity:

https://github.com/RogueOneEcho/caesura/blob/f39737191850b1b2398c5048561c35958a4e3550/src/options/shared_options.rs#L142

**Comment by quig-official** [comment]
I'm not rushing you or anything. Just letting you know that RED has re-enabled upload.

**Comment by quig-official** [comment]
I'm not sure how far off you have forked from it. But, Red_oxide has update their code. You could potentially merge their changes..?
https://github.com/DevYukine/red_oxide/releases/tag/v0.9.1

**Comment by RogueOneEcho** [comment]
> I'm not sure how far off you have forked from it. But, Red_oxide has update their code. You could potentially merge their changes..? https://github.com/DevYukine/red_oxide/releases/tag/v0.9.1


`caesura` has deviated way to far from `red_oxide` to be able to merge changes. I doubt there are any files that haven't been rewritten or re-structured.

> Edit: I thought I had said it already. Adding `indexer_url: https://redacted.sh` to config.yml worked.

It might work for new torrents but there will be issues using the `batch` command to read existing torrents as the existing torrents on your system will contain `.ch` URL while the API needs `.sh` etc.

**Comment by RogueOneEcho** [comment]
Resolved in https://github.com/RogueOneEcho/caesura/releases/tag/v0.22.0

Now that red_oxide is actively maintained again I'll create a new thread on RED (soon) to announce the update
